# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZuPro2Flex
author: Adrian Singer
claim: '{Code} [Blog] _Live_'
email: adrian.singer@iwu.fraunhofer.de
subject: ZuPro2Flex

description: > # this means to ignore newlines until "baseurl:"
  Das vom BMBF geförderte Projekt ZuPro2Flex befasst sich mit der Zustandsbewertung und
  Prozessassistenz für nutzungsdauerbasierte Geschäftsmodelle zur Flexibilitätssteigerung in der Produktion.

permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  
# Build settings
markdown: kramdown
exclude: ["README.md"]

sass:
    style: compressed

highlighter: rouge